### ISSUE TITLE
19/01/2022

### ISSUE THREAD

**Issue by ravi-hamidov** [RovsenRzali/PragmatechFoundationProject#9]
https://github.com/RovsenRzali/PragmatechFoundationProject/blob/4c9f87ecd01ae2f633d47cd39fbb811d9976eefc/Works/Task04_Flexbox_Grid_Selectors/first%20task/css/selectors.css#L1

Demeli Rovsen burda Task dogrudur , lakin daha yaxsi olardi ki asagida yazdiqim kod numunesini nezerden kecirdesen , yeni bu taskda sadece 2 div e reng vermek teleb olunub amma butun div lerin hamisina muxtelif renglerin verilmeside teleb oluna bilerdi meselen ferz etki 40 dene div var ve bunlarin hamisina adlandirmaq coxda dogru yazilis deil

```css
div:nth-child(2)>ul>li:nth-child(1) {
    background-color: yellow;
}

div:nth-child(4)>ul>li:nth-child(3) {
    background-color: red;
}
```
